on: push

permissions:
    contents: write
    packages: write

jobs:
  release-linux-arm:
    name: release linux/arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm
        goarm: 6
        project_path: server
